name: Autoformat with Black and Create PR

on: [push, pull_request]

jobs:
  format-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Black
        run: python -m pip install black

      - name: Format code with Black
        run: black --verbose .

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "No changes to format"
            echo "::set-output name=changes_exist::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes_exist::true"
          fi

      - name: Commit formatted code
        if: steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Apply autoformatting with Black"
          # Assuming you want to push to the same branch
          # Create a unique branch name if necessary
          git push origin HEAD:${{ github.head_ref }}

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply autoformatting with Black"
          title: "Autoformatting with Black"
          body: "This PR applies Black formatting to the code."
          branch: "format/${{ github.head_ref }}-${{ github.run_number }}"
          delete-branch: true
          draft: false
